
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ctans
 */
public class AddNewCarScreen extends javax.swing.JFrame {

    /**
     * Creates new form AddNewCarScreen
     */
    public AddNewCarScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        EDIT = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        car_color_text = new javax.swing.JTextField();
        car_model_text = new javax.swing.JTextField();
        car_brand_text = new javax.swing.JTextField();
        car_price_text = new javax.swing.JTextField();
        car_motorpower_text = new javax.swing.JTextField();
        add_new_car_button = new javax.swing.JButton();
        closebutton = new javax.swing.JButton();
        deletebutton = new javax.swing.JButton();
        edıt_button = new javax.swing.JButton();
        car_availabilty = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        car_info_table = new javax.swing.JTable();
        showbutton = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("COLOR : ");

        jLabel2.setText("MODEL :");

        jLabel3.setText("BRAND : ");

        jLabel4.setText("PRICE FOR RENT : ");

        jLabel5.setText("MOTOR POWER :");

        car_motorpower_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                car_motorpower_textActionPerformed(evt);
            }
        });

        add_new_car_button.setText("ADD");
        add_new_car_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_new_car_buttonActionPerformed(evt);
            }
        });

        closebutton.setText("CLOSE");
        closebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebuttonActionPerformed(evt);
            }
        });

        deletebutton.setText("DELETE");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });

        edıt_button.setText("EDIT");
        edıt_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edıt_buttonActionPerformed(evt);
            }
        });

        car_availabilty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YES", "NO" }));
        car_availabilty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                car_availabiltyActionPerformed(evt);
            }
        });

        jLabel6.setText("AVAILABLE : ");

        javax.swing.GroupLayout EDITLayout = new javax.swing.GroupLayout(EDIT);
        EDIT.setLayout(EDITLayout);
        EDITLayout.setHorizontalGroup(
            EDITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EDITLayout.createSequentialGroup()
                .addGroup(EDITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(EDITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(car_color_text)
                    .addComponent(car_model_text)
                    .addComponent(car_brand_text, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(EDITLayout.createSequentialGroup()
                .addGroup(EDITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(EDITLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(add_new_car_button, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(edıt_button, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EDITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(EDITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(EDITLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(car_price_text, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, EDITLayout.createSequentialGroup()
                                .addGroup(EDITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(EDITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(car_availabilty, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(car_motorpower_text))))
                        .addGroup(EDITLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(deletebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(closebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EDITLayout.setVerticalGroup(
            EDITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EDITLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(EDITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(EDITLayout.createSequentialGroup()
                        .addGroup(EDITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(car_color_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(EDITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(car_model_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(EDITLayout.createSequentialGroup()
                        .addComponent(car_brand_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(EDITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(car_price_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(EDITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(car_motorpower_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EDITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(car_availabilty)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(EDITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_new_car_button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edıt_button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EDITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        car_info_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Brand", "MODEL", "COLOR", "MOTOR POWER", "PRICE", "AVAILABLE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        car_info_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                car_info_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(car_info_table);
        if (car_info_table.getColumnModel().getColumnCount() > 0) {
            car_info_table.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        showbutton.setText("Show Car List");
        showbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EDIT, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(showbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EDIT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(24, 24, 24))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebuttonActionPerformed
        AdminMenüScreen adminmenüscreen = new AdminMenüScreen();
        adminmenüscreen.setVisible(true);
    }//GEN-LAST:event_closebuttonActionPerformed

    private void add_new_car_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_new_car_buttonActionPerformed
        ArrayList<Car> car_list = MainScreen.getCars() ;
        DefaultTableModel model = (DefaultTableModel)car_info_table.getModel();
        int id = car_list.size()+1 ;
        
        String  ID = new String(Integer.toString(id));        
        String brand = new String(car_brand_text.getText());
        String car_model = new String(car_model_text.getText());
        String  color = new String(car_color_text.getText());
        String motor_power = new String(car_motorpower_text.getText());
        Integer rent_price = new Integer(car_price_text.getText());

        Boolean available ;
        if (car_availabilty.getSelectedItem().equals("YES")) {
            available = true ;
        }
        else{
            available = false ;
        }
        
        car_list.add(new Car(ID,brand,car_model,color,motor_power,rent_price,available));
        model.addRow(new Object[]{ID,brand,car_model,color,motor_power,rent_price,car_availabilty.getSelectedItem().toString()});
        JOptionPane.showMessageDialog(this,"CAR HAS ADDED ");
    }//GEN-LAST:event_add_new_car_buttonActionPerformed

    private void car_motorpower_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_car_motorpower_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_car_motorpower_textActionPerformed

    private void edıt_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edıt_buttonActionPerformed
        DefaultTableModel model = (DefaultTableModel)car_info_table.getModel();
        ArrayList<Car> car_list = MainScreen.getCars() ;
        
        int choosen_row = car_info_table.getSelectedRow();

        if (choosen_row == -1) {
            if (car_info_table.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this,"Car table is empty ");
            }else{
                JOptionPane.showMessageDialog(this," Please choose a car to edit " );
            }
        }
        else{
        String brand = new String(car_brand_text.getText());
        String car_model = new String(car_model_text.getText());
        String  color = new String(car_color_text.getText());
        String motor_power = new String(car_motorpower_text.getText());
        Integer rent_price = new Integer(car_price_text.getText());
           
        Car edit_car = new Car(brand,car_model,color,motor_power,rent_price);
            
           model.setValueAt(brand,choosen_row ,0);
           model.setValueAt(car_model,choosen_row ,1);
           model.setValueAt(color ,choosen_row ,2);
           model.setValueAt(motor_power,choosen_row ,3);
           model.setValueAt(rent_price ,choosen_row ,4);
           
           
           
           car_list.set(choosen_row , edit_car);
           
        }
        

        
    }//GEN-LAST:event_edıt_buttonActionPerformed

    private void showbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showbuttonActionPerformed
        DefaultTableModel model = (DefaultTableModel)car_info_table.getModel();
        ArrayList<Car> car_list = MainScreen.getCars() ;
        
        
        for(int i = 0 ; i < car_list.size() ; i++){
            model.addRow(new Object[]{car_list.get(i).getCar_ıd(),car_list.get(i).getBrand(),car_list.get(i).getModel(),car_list.get(i).getColor(),car_list.get(i).getMotor_power(),car_list.get(i).getDaily_rent_price(),car_list.get(i).getAvailable()});
        }
    }//GEN-LAST:event_showbuttonActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        DefaultTableModel model = (DefaultTableModel)car_info_table.getModel();
        ArrayList<Car> car_list = MainScreen.getCars() ;
        
        int choosen_row = car_info_table.getSelectedRow();

        if (choosen_row == -1) {
            if (car_info_table.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this,"Car table is empty ");
            }else{
                JOptionPane.showMessageDialog(this,"Please choose a car to remove from list " );
            }
        }else{
            for (int i = 0; i < car_list.size() ; i++) {
                if (car_list.get(choosen_row).getCar_ıd().equals(car_list.get(i).getCar_ıd())) {
                    model.removeRow(choosen_row);
                    car_list.remove(i);
                    JOptionPane.showMessageDialog(this,"CAR HAS DELETED" );
                    break;
                }
            }  
        }
    }//GEN-LAST:event_deletebuttonActionPerformed

    private void car_availabiltyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_car_availabiltyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_car_availabiltyActionPerformed

    private void car_info_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_car_info_tableMouseClicked
        DefaultTableModel model = (DefaultTableModel)car_info_table.getModel();
        
        int choosen_row = car_info_table.getSelectedRow();
        
        car_brand_text.setText(model.getValueAt(choosen_row,1).toString());
        car_model_text.setText(model.getValueAt(choosen_row,2).toString());
        car_color_text.setText(model.getValueAt(choosen_row,3).toString());
        car_motorpower_text.setText(model.getValueAt(choosen_row,4).toString());
        car_price_text.setText(model.getValueAt(choosen_row,5).toString());
        
    }//GEN-LAST:event_car_info_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewCarScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewCarScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewCarScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewCarScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewCarScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EDIT;
    private javax.swing.JButton add_new_car_button;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox<String> car_availabilty;
    private javax.swing.JTextField car_brand_text;
    private javax.swing.JTextField car_color_text;
    private javax.swing.JTable car_info_table;
    private javax.swing.JTextField car_model_text;
    private javax.swing.JTextField car_motorpower_text;
    private javax.swing.JTextField car_price_text;
    private javax.swing.JButton closebutton;
    private javax.swing.JButton deletebutton;
    private javax.swing.JButton edıt_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton showbutton;
    // End of variables declaration//GEN-END:variables
}
